### ISSUE TITLE
i18n/l10n

### ISSUE THREAD

**Issue by Cladis** [Toollabs/relgen#6] opened 2016-12-16 17:56 UTC
Make it internationalised/localisable please! :)

**Comment by ValentinBrclz** [comment] 2016-12-17 18:01
I strongly support this feature request. There is a huge need for FR users (at least) and probably DE ones too.

A translation for Polish [just got requested](https://commons.wikimedia.org/w/index.php?title=User_talk:FDMS4&curid=26444671&diff=227133996&oldid=226410592) too.

**Comment by FDMS** [comment] 2016-12-22 20:14
Thanks for the suggestion – please take a look at this brand new [FAQ entry](https://github.com/toollabs/relgen#frequently-asked-questions).

**Comment by ValentinBrclz** [comment] 2016-12-22 20:44
I would agree, but Wikimedia Commons has the exact same procedure for every language and this could be at use for this specific purpose (which is the main one for files anyway, Wikipedias and other projects are only hosting exceptions like fair use).

Aren't you afraid that the duplicate of `index.php` will have to be updated at the same time of the original one that this would create a huge mess?!

**Comment by FDMS** [comment] 2016-12-22 20:57
I'm afraid there'll be somewhat of a mess either way given that Commons' release template language versions are quite hopelessly out of sync. Even if they weren't, an approach similar to the MediaWiki Translation Extension would make translations incomplete or even obsolete each time there is a tool update affecting texts.

(I had this [Wikipedia prototype](http://t.fdms.eu/relgen/wp.php) in mind when writing "language editions of Wikimedia projects".)

**Comment by ValentinBrclz** [comment] 2016-12-22 21:01
I see and understand, this makes sense. Could you then add a free license to your repo so that we can fork it ? :-)

**Comment by FDMS** [comment] 2016-12-22 21:16
relgen is under the EUPL 1.1, this should now also be machine-readable thanks to the newly created LICENSE.txt file (and the Licensee API).

**Closed as completed by FDMS** 2016-12-22 21:16 UTC

**Comment by Cladis** [comment] 2016-12-23 00:13
Hi. What do you mean by different release templates? There are several points to consider:
* The permission text is supposed to be standard one, isn't it. For example in ukwiki we do have its versions, e.g. specific version targeted at architects who want to enable FOP for their works but it is still basically the same.
* Permissions are not bound specific project, actually it is just the language what matters.
  * For example you can write permission in Russian, with russian permission text releasing a book in Japanese you have written and though it concerns Japanese Wikipedia/Wikisource it would be proceeded by Russian OTRS-query probably as they are language bound, not specific Wikipedia bound (or by both ru and ja in case Russian agents get scared for this theoretical example :) ).
  * Sometimes frequent users of OTRS choose to use another language to have to deal with different OTRS agents (e.g. some Ukrainian users have unrelated personal grudges with some of Ukrainian agents), despite intending to use works in the same wiki. While it may be weird, it is still perfectly fine (unless other circumstances do it fine not).
* And it is so much Commons centered anyway.
* The templates to be placed afterwards indeed can differ, but it is the work of OTRS agents to take care of. I think at least providing just translation of Commons based standard most permission text is the best option.
* The supplementary interface text is not dependent on anything at all.

Well, forking index.php is definitely an option and thank you for that, but I would still very much prefer application logic and messages to be separate. It may not look like this for you, but the extension translate approach where some parts are getting untranslated is actually not that bad, and definitely easier to maintain for translators than having to re-fork index.php and reinsert translations in case some major application logic change has occurred.

I am sorry if it all sounds a bit rough and too demanding, it is just that the tool is really cool and I want an easy way to have it used by speakers of my language too, without having to employ that little skills in PHP I have ^_^

**Comment by zhuyifei1999** [comment] 2016-12-23 07:29
You might want to try integrating with [intuition](https://tools.wmflabs.org/intuition/) + translatewiki

**Comment by FDMS** [comment] 2016-12-23 14:26
The different language versions of the release template on Commons don't just use different terminology, but differ significantly in terms of options, content and overall structure.

I don't really see a point in offering a partially translated version – as someone who doesn't understand Arabic I most likely wouldn't be able to use an Arabic GUI even if _parts of it_ were translated into English. Furthermore, I'd imagine software with the same GUI being displayed in different languages to be quite a usability nightmare.

For tool updates only affecting logics translations could be saved in a structured format and easily applied to the subsequent re-forks using search and replace (I'd take care of that).

**Comment by abartov** [comment] 2019-03-15 11:11
Now that some translations have been contributed, it would be good to reconsider making the tool launchable with a particular language.  This would presumably mean extracting the strings from the code and using one of the many standard I18N libraries for PHP (not necessarily going all the way to integrating with TranslateWiki).

As it stands, I don't see how to get the contributed translations used, other than hosting a separate relgen instance with the translated index.php instead of the main one.  I could do it, but smaller communities without technical volunteers would find it difficult, and anyway, a single codebase is safer and won't fall out of date.

Would you be able to devote some time to that?  If not, we may be able to recruit another developer to help accomplish it.

**Comment by FDMS** [comment] 2019-03-18 19:23
Sorry for the delayed response. Not sure I understand you correctly, but the contributed translations _can_ be used through a subpage of the same relgen instance (c.f. e.g. [es](https://tools.wmflabs.org/relgen/i18n/es.php) – yes, through its own .php file). The translated versions of relgen seem to be used [occasionally](https://tools.wmflabs.org/relgen/stats.php) (c.f. notes column).

While I believe the concerns wrt 1:1 translations I explained above are still valid, regardless of those I do not currently intend to invest significant amounts of time into the PHP-based version of relgen, since as I wrote [here](https://commons.wikimedia.org/wiki/User_talk:FDMS4/archive/2019/I), _the PHP-based version of the tool will be superseded by a JS-based version of the tool (that I finished in July 2018, *cough*) soon™_. The source code of said JS-based version with some additional features is available [here](https://commons.wikimedia.beta.wmflabs.org/wiki/User:FDMS_(2017-08-17)/test) (to be moved to the MW ns on Commons and used with `withJS=`). I guess such an onwiki approach would make translations easier to provide?

**Comment by abartov** [comment] 2019-05-07 09:52
Thank you for this clarification!  The URL was difficult to guess.

I am glad to learn about the JS version. I was not aware of it.  However, having just tried it, I do not see that that version has localization either.  I changed my language to Spanish in my Preferences on Commons, and went to [[c:COM:relgen]], but was still given the English text.  So, is that text localizable somewhere?

**Comment by FDMS** [comment] 2019-05-14 19:39
Not yet, but as stated in the [Village pump announcement](https://commons.wikimedia.org/wiki/Commons:Village_pump/Archive/2019/04#New_Wikimedia_OTRS_release_generator_now_live_on_Commons), adding internationalisation support definitely is a priority.

**Comment by FDMS** [comment] 2019-07-06 00:00
As of today, relgen.js now has a translation interface (based on the MW Messages API and user language preferences) – to add a translation, please provide a translated version of [MediaWiki:Relgen.js/text](https://commons.wikimedia.org/wiki/MediaWiki:Relgen.js/text)
